### ISSUE TITLE
`c_code` directories missing from `package_data`

### ISSUE THREAD

**Issue by eganster** [aesara-devs/aesara#1182]
It seems like some `c_code` directories (namely `aesara/scalar/c_code`, `aesara/scan/c_code` and `aesara/tensor/c_code`) are missing when installing version 2.8.3:

Minimum example:
```python
import aesara.tensor
import numpy as np

aesara.tensor.gt(np.linspace(0, 1, 10), 0.5)
```

Traceback:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/graph/op.py", line 297, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/tensor/elemwise.py", line 481, in make_node
    out_dtypes, out_shapes, inputs = self.get_output_info(DimShuffle, *inputs)
  File "/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/tensor/elemwise.py", line 408, in get_output_info
    dim_shuffle(
  File "/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/tensor/elemwise.py", line 130, in __init__
    super().__init__([self.c_func_file], self.c_func_name)
  File "/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/link/c/op.py", line 334, in __init__
    self.load_c_code(self.func_files)
  File "/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/link/c/op.py", line 355, in load_c_code
    with open(func_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/virtualenvs/test/lib/python3.10/site-packages/aesara/tensor/c_code/dimshuffle.c'
```

I think this bug was introduced in #1135: The "old"
```python
        package_data={
            "": [
                "*.txt",
                ...
            ],
```

should be
```python
[options.package_data]
* =
    *.txt
     ....
```
as otherwise only the `aesara` directory is searched for the listed files/directories, but not any subdirectories such that  `aesara/scalar/c_code`, `aesara/scan/c_code` and `aesara/tensor/c_code` are not picked up (see also the [setuptools docu on package_data](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data)).

## Versions and main components

* Aesara version: 2.8.3
* Aesara config: Fresh install, no user specific settings
* Python version: 3.10
* Operating system: Linux
* How did you install Aesara: pip

**Comment by brandonwillard** [comment]
Good find; much appreciated!

**Comment by maresb** [comment]
Oops, thanks for catching that!!!
