### ISSUE TITLE
Memory leak with a particular combination of operations

### ISSUE THREAD

**Issue by mattearllongshot** [aesara-devs/aesara#1517]
## Description of your problem or feature request

With a particular combination of subtensor / matrix multiplication / scalar multiplication / gradient operations (see below for details) approximately 128 bytes of memory are leaked per function evaluation.

Setup a fresh conda environment with these steps:

```bash
conda create -n leak
conda activate leak
conda install -c conda-forge aesara
pip install psutil
```

Then run the following script:

```python
import aesara
import aesara.tensor as at
import numpy as np
import psutil


mask_shape = (3,)
mulvec_shape = (2,)
matrix_shape = (3, 2)


def mk_fun():
    mask = aesara.shared(np.zeros(mask_shape, dtype=bool))
    mulvec = aesara.shared(np.zeros(mulvec_shape))
    matrix = aesara.shared(np.zeros(matrix_shape))

    scale = at.as_tensor(np.ones(mask_shape))

    invec = at.vector()
    invec_masked = invec[mask]
    masked_output = (
        (invec_masked[:, None] * matrix) @ mulvec
        * scale[mask]
    )
    output = at.zeros_like(invec)
    output = at.set_subtensor(output[mask], masked_output)

    fun_and_grad = aesara.function([invec], at.grad(at.sum(output), invec))

    mask.set_value(np.ones(mask_shape, dtype=bool))
    mulvec.set_value(np.ones(mulvec_shape))
    matrix.set_value(np.ones(matrix_shape))

    return fun_and_grad


fun = mk_fun()


proc = psutil.Process()

print('memory usage before', proc.memory_info().rss / (1 << 20), 'MB')
for i in range(1_000_000):
    fun(np.zeros(mask_shape))
print('memory usage after', proc.memory_info().rss / (1 << 20), 'MB')
```

This produces the following output:

```python
memory usage before 119.4296875 MB
memory usage after 241.703125 MB
```

I've tried to reduce the example even further but this is as small as I could make it.  Hopefully you can make some sense of it!

## Versions and main components

* Aesara version: 2.9.2
* Python version: Python 3.11.6
* Operating system: Ubuntu 18.04.6 LTS
* How did you install Aesara: conda

<details> <summary> Aesara config: </summary>

Place the results of `python -c "import aesara; print(aesara.config)"` here.
```
floatX ({'float32', 'float16', 'float64'})
    Doc:  Default floating-point precision for python casts.

Note: float16 support is experimental, use at your own risk.
    Value:  float64

warn_float64 ({'warn', 'raise', 'ignore', 'pdb'})
    Doc:  Do an action when a tensor variable with float64 dtype is created.
    Value:  ignore

pickle_test_value (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fcc511d0>>)
    Doc:  Dump test values while pickling model. If True, test values will be dumped with model.
    Value:  True

cast_policy ({'custom', 'numpy+floatX'})
    Doc:  Rules for implicit type casting
    Value:  custom

deterministic ({'default', 'more'})
    Doc:  If `more`, sometimes we will select some implementation that are more deterministic, but slower.  Also see the dnn.conv.algo* flags to cover more cases.
    Value:  default

device (cpu)
    Doc:  Default device for computations. only cpu is supported for now
    Value:  cpu

force_device (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fba5d428850>>)
    Doc:  Raise an error if we can't use the specified device
    Value:  False

conv__assert_shape (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2750>>)
    Doc:  If True, AbstractConv* ops will verify that user-provided shapes match the runtime shapes (debugging option, may slow down compilation)
    Value:  False

print_global_stats (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2850>>)
    Doc:  Print some global statistics (time spent) at the end
    Value:  False

assert_no_cpu_op ({'warn', 'raise', 'ignore', 'pdb'})
    Doc:  Raise an error/warning if there is a CPU op in the computational graph.
    Value:  ignore

unpickle_function (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2810>>)
    Doc:  Replace unpickled Aesara functions with None. This is useful to unpickle old graphs that pickled them when it shouldn't
    Value:  True

<aesara.configparser.ConfigParam object at 0x7fb9fbee29d0>
    Doc:  Default compilation mode
    Value:  Mode

cxx (<class 'str'>)
    Doc:  The C++ compiler to use. Currently only g++ is supported, but supporting additional compilers should not be too difficult. If it is empty, no C++ code is compiled.
    Value:  /mnt/data/conda/envs/aesarabug/bin/g++

linker ({'vm', 'py', 'c|py_nogc', 'c', 'c|py', 'cvm', 'cvm_nogc', 'vm_nogc'})
    Doc:  Default linker used if the aesara flags mode is Mode
    Value:  cvm

allow_gc (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fba04e81310>>)
    Doc:  Do we default to delete intermediate results during Aesara function calls? Doing so lowers the memory requirement, but asks that we reallocate memory at the next function call. This is implemented for the default linker, but may not work for all linkers.
    Value:  True

optimizer ({'merge', 'o3', 'fast_compile', 'None', 'o1', 'o4', 'unsafe', 'fast_run', 'o2'})
    Doc:  Default optimizer. If not None, will use this optimizer with the Mode
    Value:  o4

optimizer_verbose (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fcd61150>>)
    Doc:  If True, we print all optimization being applied
    Value:  False

on_opt_error ({'pdb', 'ignore', 'raise', 'warn'})
    Doc:  What to do when an optimization crashes: warn and skip it, raise the exception, or fall into the pdb debugger.
    Value:  warn

nocleanup (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2b90>>)
    Doc:  Suppress the deletion of code files that did not compile cleanly
    Value:  False

on_unused_input ({'ignore', 'raise', 'warn'})
    Doc:  What to do if a variable in the 'inputs' list of  aesara.function() is not used in the graph.
    Value:  raise

gcc__cxxflags (<class 'str'>)
    Doc:  Extra compiler flags for gcc
    Value:

cmodule__warn_no_version (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fcdd12d0>>)
    Doc:  If True, will print a warning when compiling one or more Op with C code that can't be cached because there is no c_code_cache_version() function associated to at least one of those Ops.
    Value:  False

cmodule__remove_gxx_opt (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2a10>>)
    Doc:  If True, will remove the -O* parameter passed to g++.This is useful to debug in gdb modules compiled by Aesara.The parameter -g is passed by default to g++
    Value:  False

cmodule__compilation_warning (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2f50>>)
    Doc:  If True, will print compilation warnings.
    Value:  False

cmodule__preload_cache (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee2f90>>)
    Doc:  If set to True, will preload the C module cache at import time
    Value:  False

cmodule__age_thresh_use (<class 'int'>)
    Doc:  In seconds. The time after which Aesara won't reuse a compile c module.
    Value:  2073600

cmodule__debug (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3110>>)
    Doc:  If True, define a DEBUG macro (if not exists) for any compiled C code.
    Value:  False

compile__wait (<class 'int'>)
    Doc:  Time to wait before retrying to acquire the compile lock.
    Value:  5

compile__timeout (<class 'int'>)
    Doc:  In seconds, time that a process will wait before deciding to
    override an existing lock. An override only happens when the existing
    lock is held by the same owner *and* has not been 'refreshed' by this
    owner for more than this period. Refreshes are done every half timeout
    period for running processes.
    Value:  120

ctc__root (<class 'str'>)
    Doc:  Directory which contains the root of Baidu CTC library. It is assumed         that the compiled library is either inside the build, lib or lib64         subdirectory, and the header inside the include directory.
    Value:

tensor__cmp_sloppy (<class 'int'>)
    Doc:  Relax aesara.tensor.math._allclose (0) not at all, (1) a bit, (2) more
    Value:  0

tensor__local_elemwise_fusion (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3550>>)
    Doc:  Enable or not in fast_run mode(fast_run optimization) the elemwise fusion optimization
    Value:  True

lib__amblibm (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3590>>)
    Doc:  Use amd's amdlibm numerical library
    Value:  False

tensor__insert_inplace_optimizer_validate_nb (<class 'int'>)
    Doc:  -1: auto, if graph have less then 500 nodes 1, else 10
    Value:  -1

traceback__limit (<class 'int'>)
    Doc:  The number of stack to trace. -1 mean all.
    Value:  8

traceback__compile_limit (<class 'int'>)
    Doc:  The number of stack to trace to keep during compilation. -1 mean all. If greater then 0, will also make us save Aesara internal stack trace.
    Value:  0

experimental__local_alloc_elemwise (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3810>>)
    Doc:  DEPRECATED: If True, enable the experimental optimization local_alloc_elemwise. Generates error if not True. Use optimizer_excluding=local_alloc_elemwise to disable.
    Value:  True

experimental__local_alloc_elemwise_assert (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3ad0>>)
    Doc:  When the local_alloc_elemwise is applied, add an assert to highlight shape errors.
    Value:  True

warn__ignore_bug_before ({'all', 'None', '1.0.1', '0.9', '0.7', '0.10', '1.0.2', '0.4.1', '0.8.1', '0.8.2', '0.3', '1.0.4', '0.8', '0.5', '0.6', '0.4', '1.0', '1.0.5', '1.0.3'})
    Doc:  If 'None', we warn about all Aesara bugs found by default. If 'all', we don't warn about Aesara bugs found by default. If a version, we print only the warnings relative to Aesara bugs found after that version. Warning for specific bugs can be configured with specific [warn] flags.
    Value:  0.9

exception_verbosity ({'high', 'low'})
    Doc:  If 'low', the text of exceptions will generally refer to apply nodes with short names such as Elemwise{add_no_inplace}. If 'high', some exceptions will also refer to apply nodes with long descriptions  like:
        A. Elemwise{add_no_inplace}
                B. log_likelihood_v_given_h
                C. log_likelihood_h
    Value:  low

print_test_value (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3c50>>)
    Doc:  If 'True', the __eval__ of an Aesara variable will return its test_value when this is available. This has the practical conseguence that, e.g., in debugging `my_var` will print the same as `my_var.tag.test_value` when a test value is defined.
    Value:  False

compute_test_value ({'raise', 'warn', 'ignore', 'pdb', 'off'})
    Doc:  If 'True', Aesara will run each op at graph build time, using Constants, SharedVariables and the tag 'test_value' as inputs to the function. This helps the user track down problems in the graph before it gets optimized.
    Value:  off

compute_test_value_opt ({'raise', 'warn', 'ignore', 'pdb', 'off'})
    Doc:  For debugging Aesara optimization only. Same as compute_test_value, but is used during Aesara optimization
    Value:  off

check_input (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fba5d2bdbd0>>)
    Doc:  Specify if types should check their input in their C code. It can be used to speed up compilation, reduce overhead (particularly for scalars) and reduce the number of generated C files.
    Value:  True

NanGuardMode__nan_is_error (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fcb813d0>>)
    Doc:  Default value for nan_is_error
    Value:  True

NanGuardMode__inf_is_error (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef40d0>>)
    Doc:  Default value for inf_is_error
    Value:  True

NanGuardMode__big_is_error (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef4090>>)
    Doc:  Default value for big_is_error
    Value:  True

NanGuardMode__action ({'pdb', 'raise', 'warn'})
    Doc:  What NanGuardMode does when it finds a problem
    Value:  raise

DebugMode__patience (<class 'int'>)
    Doc:  Optimize graph this many times to detect inconsistency
    Value:  10

DebugMode__check_c (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef42d0>>)
    Doc:  Run C implementations where possible
    Value:  True

DebugMode__check_py (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fba04e81390>>)
    Doc:  Run Python implementations where possible
    Value:  True

DebugMode__check_finite (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef45d0>>)
    Doc:  True -> complain about NaN/Inf results
    Value:  True

DebugMode__check_strides (<class 'int'>)
    Doc:  Check that Python- and C-produced ndarrays have same strides. On difference: (0) - ignore, (1) warn, or (2) raise error
    Value:  0

DebugMode__warn_input_not_reused (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef4790>>)
    Doc:  Generate a warning when destroy_map or view_map says that an op works inplace, but the op did not reuse the input for its output.
    Value:  True

DebugMode__check_preallocated_output (<class 'str'>)
    Doc:  Test thunks with pre-allocated memory as output storage. This is a list of strings separated by ":". Valid values are: "initial" (initial storage in storage map, happens with Scan),"previous" (previously-returned memory), "c_contiguous", "f_contiguous", "strided" (positive and negative strides), "wrong_size" (larger and smaller dimensions), and "ALL" (all of the above).
    Value:

DebugMode__check_preallocated_output_ndim (<class 'int'>)
    Doc:  When testing with "strided" preallocated output memory, test all combinations of strides over that number of (inner-most) dimensions. You may want to reduce that number to reduce memory or time usage, but it is advised to keep a minimum of 2.
    Value:  4

profiling__time_thunks (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef4890>>)
    Doc:  Time individual thunks when profiling
    Value:  True

profiling__n_apply (<class 'int'>)
    Doc:  Number of Apply instances to print by default
    Value:  20

profiling__n_ops (<class 'int'>)
    Doc:  Number of Ops to print by default
    Value:  20

profiling__output_line_width (<class 'int'>)
    Doc:  Max line width for the profiling output
    Value:  512

profiling__min_memory_size (<class 'int'>)
    Doc:  For the memory profile, do not print Apply nodes if the size
                 of their outputs (in bytes) is lower than this threshold
    Value:  1024

profiling__min_peak_memory (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef4c50>>)
    Doc:  The min peak memory usage of the order
    Value:  False

profiling__destination (<class 'str'>)
    Doc:  File destination of the profiling output
    Value:  stderr

profiling__debugprint (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fcc3ac50>>)
    Doc:  Do a debugprint of the profiled functions
    Value:  False

profiling__ignore_first_call (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef4f10>>)
    Doc:  Do we ignore the first call of an Aesara function.
    Value:  False

on_shape_error ({'raise', 'warn'})
    Doc:  warn: print a warning and use the default value. raise: raise an error
    Value:  warn

openmp (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef4f50>>)
    Doc:  Allow (or not) parallel computation on the CPU with OpenMP. This is the default value used when creating an Op that supports OpenMP parallelization. It is preferable to define it via the Aesara configuration file ~/.aesararc or with the environment variable AESARA_FLAGS. Parallelization is only done for some operations that implement it, and even for operations that implement parallelism, each operation is free to respect this flag or not. You can control the number of threads used with the environment variable OMP_NUM_THREADS. If it is set to 1, we disable openmp in Aesara by default.
    Value:  False

openmp_elemwise_minsize (<class 'int'>)
    Doc:  If OpenMP is enabled, this is the minimum size of vectors for which the openmp parallelization is enabled in element wise ops.
    Value:  200000

optimizer_excluding (<class 'str'>)
    Doc:  When using the default mode, we will remove optimizer with these tags. Separate tags with ':'.
    Value:

optimizer_including (<class 'str'>)
    Doc:  When using the default mode, we will add optimizer with these tags. Separate tags with ':'.
    Value:

optimizer_requiring (<class 'str'>)
    Doc:  When using the default mode, we will require optimizer with these tags. Separate tags with ':'.
    Value:

optdb__position_cutoff (<class 'float'>)
    Doc:  Where to stop eariler during optimization. It represent the position of the optimizer where to stop.
    Value:  inf

optdb__max_use_ratio (<class 'float'>)
    Doc:  A ratio that prevent infinite loop in EquilibriumGraphRewriter.
    Value:  8.0

cycle_detection ({'fast', 'regular'})
    Doc:  If cycle_detection is set to regular, most inplaces are allowed,but it is slower. If cycle_detection is set to faster, less inplacesare allowed, but it makes the compilation faster.The interaction of which one give the lower peak memory usage iscomplicated and not predictable, so if you are close to the peakmemory usage, triyng both could give you a small gain.
    Value:  regular

check_stack_trace ({'raise', 'off', 'warn', 'log'})
    Doc:  A flag for checking the stack trace during the optimization process. default (off): does not check the stack trace of any optimization log: inserts a dummy stack trace that identifies the optimizationthat inserted the variable that had an empty stack trace.warn: prints a warning if a stack trace is missing and also a dummystack trace is inserted that indicates which optimization insertedthe variable that had an empty stack trace.raise: raises an exception if a stack trace is missing
    Value:  off

metaopt__verbose (<class 'int'>)
    Doc:  0 for silent, 1 for only warnings, 2 for full output withtimings and selected implementation
    Value:  0

metaopt__optimizer_excluding (<class 'str'>)
    Doc:  exclude optimizers with these tags. Separate tags with ':'.
    Value:

metaopt__optimizer_including (<class 'str'>)
    Doc:  include optimizers with these tags. Separate tags with ':'.
    Value:

profile (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fc2fafd0>>)
    Doc:  If VM should collect profile information
    Value:  False

profile_optimizer (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef54d0>>)
    Doc:  If VM should collect optimizer profile information
    Value:  False

profile_memory (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbee3310>>)
    Doc:  If VM should collect memory profile information and print it
    Value:  False

<aesara.configparser.ConfigParam object at 0x7fb9fce06050>
    Doc:  Useful only for the VM Linkers. When lazy is None, auto detect if lazy evaluation is needed and use the appropriate version. If the C loop isn't being used and lazy is True, use the Stack VM; otherwise, use the Loop VM.
    Value:  None

unittests__rseed (<class 'str'>)
    Doc:  Seed to use for randomized unit tests. Special value 'random' means using a seed of None.
    Value:  666

warn__round (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef5710>>)
    Doc:  Warn when using `tensor.round` with the default mode. Round changed its default from `half_away_from_zero` to `half_to_even` to have the same default as NumPy.
    Value:  False

numba__vectorize_target ({'cuda', 'cpu', 'parallel'})
    Doc:  Default target for numba.vectorize.
    Value:  cpu

numba__fastmath (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef5950>>)
    Doc:  If True, use Numba's fastmath mode.
    Value:  True

numba__cache (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbef5890>>)
    Doc:  If True, use Numba's file based caching.
    Value:  True

compiledir_format (<class 'str'>)
    Doc:  Format string for platform-dependent compiled module subdirectory
(relative to base_compiledir). Available keys: aesara_version, device,
gxx_version, hostname, numpy_version, platform, processor,
python_bitwidth, python_int_bitwidth, python_version, short_platform.
Defaults to compiledir_%(short_platform)s-%(processor)s-
%(python_version)s-%(python_bitwidth)s.
    Value:  compiledir_%(short_platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s

<aesara.configparser.ConfigParam object at 0x7fb9fc29ca90>
    Doc:  platform-independent root directory for compiled modules
    Value:  /home/matthew/.aesara

<aesara.configparser.ConfigParam object at 0x7fb9fc1cd190>
    Doc:  platform-dependent cache directory for compiled modules
    Value:  /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.27-x86_64-3.11.6-64

blas__ldflags (<class 'str'>)
    Doc:  lib[s] to include for [Fortran] level-3 blas implementation
    Value:  -L/mnt/data/conda/envs/aesarabug/lib -lcblas -lblas -lcblas -lblas

blas__check_openmp (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fbb83dd0>>)
    Doc:  Check for openmp library conflict.
WARNING: Setting this to False leaves you open to wrong results in blas-related operations.
    Value:  True

scan__allow_gc (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9eeed5710>>)
    Doc:  Allow/disallow gc inside of Scan (default: False)
    Value:  False

scan__allow_output_prealloc (<bound method BoolParam._apply of <aesara.configparser.BoolParam object at 0x7fb9fcc39690>>)
    Doc:  Allow/disallow memory preallocation for outputs inside of scan (default: True)
    Value:  True

```
</details>

**Comment by andrejmuhic** [comment]
I have tested this a bit. It seems boolean indexing is a cause of memory leak?
Switching from boolean indexing to normal indexing seems to eliminate the leak and also probably makes things faster.
```
mask = aesara.shared(np.zeros(mask_shape, dtype=bool)) -> mask = aesara.shared(np.zeros(mask_shape[0], dtype=np.int32))
mask.set_value(np.arange(mask_shape[0], dtype=np.int32))
```

**Comment by mattearllongshot** [comment]
Hello, I've found a simpler script that reproduces the same issue, that doesn't use boolean indexing:

```python
import aesara
import aesara.tensor as at
import numpy as np
import psutil

n = 1


def mk_fun():
    mulvec = at.as_tensor(np.ones(n))
    matrix = aesara.shared(np.zeros((n, n)))

    invec = at.vector()
    output = (invec[:, None] + matrix) @ mulvec

    fun = aesara.function([invec], output)

    matrix.set_value(np.ones((n, n)))

    return fun


fun = mk_fun()

proc = psutil.Process()
print('memory usage before', proc.memory_info().rss / (1 << 20), 'MB')
for i in range(1_000_000):
    fun(np.zeros((n,)))
print('memory usage after', proc.memory_info().rss / (1 << 20), 'MB')
```

Here's the computation graph for the above snippet:
![image](https://github.com/aesara-devs/aesara/assets/37295291/e1d50905-3c3a-4935-8129-51a6d69e9038)

You can get an even simpler graph by setting `mulvec` to zeros:

```python
mulvec = at.as_tensor(np.zeros(n))
```

I think in this case the actual computation part of the graph is optimized away, since the result is always zero.  Here's the graph with zero `mulvec`:

![image](https://github.com/aesara-devs/aesara/assets/37295291/41f3ed4a-bdbc-4cc3-8994-828ec52879ba)

**Comment by brandonwillard** [comment]
@mattearllongshot, thanks; this is very helpful!

**Comment by mattearllongshot** [comment]
I've dug a bit further at this using gdb, and I may have a potential fix but I need an expert to confirm it.

I ran a python binary (with debug symbols enabled) under gdb, with the following script:
```python
import os

import aesara
import aesara.tensor as at
import numpy as np

n = 1


def mk_fun():
	mulvec = at.as_tensor(np.zeros(n))
	matrix = aesara.shared(np.zeros((n, n)))

	invec = at.vector()
	output = (invec[:, None] + matrix) @ mulvec

	fun = aesara.function([invec], output)

	matrix.set_value(np.ones((n, n)))

	return fun


fun = mk_fun()

for i in range(10):
	fun(np.zeros((n,)))

import time
import tracemalloc
tracemalloc.start()
for i in range(100):
	print('!!! ITERATION', i)
	fun(np.zeros((n,)))
print('!!! DONE')
```
It is a variation of the earlier script, only with tracemalloc enabled after a warm up.   tracemalloc alone won't print C stack traces, however if I put a gdb breakpoint at `tracemalloc_add_trace` and `tracemalloc_remove_trace`, and then have gdb print a stack trace and continue when either is hit, I'll have a log of all allocations including any in aesara compiled modules.  Each back trace starts with a line like this:

```c
#0  tracemalloc_add_trace (domain=0, ptr=140736122082896, size=48) at ./Modules/_tracemalloc.c:534
```
The pointer is the address of the memory being allocated.  I can also see the pointer in the remove trace:

```c
#0  tracemalloc_remove_trace (domain=0, ptr=140736122082896) at ./Modules/_tracemalloc.c:510
```

With a short script I can process gdb's output to work out which pointers have been allocated since the warmup without being freed.

There are two unique stack traces:

```c
100 * 96 bytes
#0  tracemalloc_add_trace () at ./Modules/_tracemalloc.c:534
#1  0x00007ffff78cb6fa in tracemalloc_alloc ()
at ./Modules/_tracemalloc.c:604
#2  0x00007ffff78cb97b in tracemalloc_alloc_gil ()
at ./Modules/_tracemalloc.c:703
#3  0x00007ffff78cb9bc in tracemalloc_malloc_gil () at ./Modules/_tracemalloc.c:713
#4  0x00007ffff77586f9 in PyObject_Malloc () at Objects/obmalloc.c:712
#5  0x00007ffff776b608 in _PyType_AllocNoTrack () at Objects/typeobject.c:1124
#6  0x00007ffff776b6d0 in PyType_GenericAlloc () at Objects/typeobject.c:1148
#7  0x00007ffff52320f0 in PyArray_NewFromDescr_int ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#8  0x00007ffff5232be0 in PyArray_NewFromDescr ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#9  0x00007ffff52a05da in PyArray_FromScalar ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#10 0x00007fffae96c545 in ()::__struct_compiled_op_m1faea6e81079ec47f312a485b2ee3da5e1d22c023ff2beb07c4da62002514c6f::run ()
at /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.27-x86_64-3.11.6+-64/tmplxsb2tpx/mod.cpp:197
#11 __struct_compiled_op_m1faea6e81079ec47f312a485b2ee3da5e1d22c023ff2beb07c4da62002514c6f_executor ()
at /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.27-x86_64-3.11.6+-64/tmplxsb2tpx/mod.cpp:313
#12 0x00007fffae15ae34 in c_call ()


100 * 8 bytes
#0  tracemalloc_add_trace () at ./Modules/_tracemalloc.c:534
#1  0x00007ffff78cd043 in PyTraceMalloc_Track () at ./Modules/_tracemalloc.c:1748
#2  0x00007ffff5212567 in PyDataMem_UserNEW ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#3  0x00007ffff523277e in PyArray_NewFromDescr_int ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#4  0x00007ffff5232be0 in PyArray_NewFromDescr ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#5  0x00007ffff52a05da in PyArray_FromScalar ()
from /home/matthew/.virtualenvs/aesara-leak/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-gnu.so
#6  0x00007fffae96c545 in ()::__struct_compiled_op_m1faea6e81079ec47f312a485b2ee3da5e1d22c023ff2beb07c4da62002514c6f::run ()
at /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.27-x86_64-3.11.6+-64/tmplxsb2tpx/mod.cpp:197
#7  __struct_compiled_op_m1faea6e81079ec47f312a485b2ee3da5e1d22c023ff2beb07c4da62002514c6f_executor ()
at /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.27-x86_64-3.11.6+-64/tmplxsb2tpx/mod.cpp:313
#8  0x00007fffae15ae34 in c_call ()
at /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.27-x86_64-3.11.6+-64/lazylinker_ext/mod.cpp:518
#9  0x00007fffae15b821 in lazy_rec_eval (self=0x7fffafd162c0, var_idx=9, one=0x7ffff7d67b28 <_PyRuntime+872>,
zero=0x7ffff7d67b08 <_PyRuntime+840>)
```

Note that both come from line 197 in one of the compiled modules.  Here's what that looks like:

```c
194 {
195 // Op class TensorFromScalar
196
197         	V1 = (PyArrayObject*)PyArray_FromScalar(py_V3, NULL);
198         	if(py_V1 == NULL){
199             	{
200     	__failure = 5;
201     	if (!PyErr_Occurred()) {
202         	PyErr_SetString(PyExc_RuntimeError,
203             	"Unexpected error in an Op's C code. "
204             	"No Python exception was set.");
205     	}
206     	goto __label_5;};
207         	}
208         	Py_XINCREF(V1);
209         	__label_5:
```

I think there may be a miscount in the references to V1, because removing the `XINCREF` apparently fixes the problem for me:

```diff
diff --git a/aesara/tensor/basic.py b/aesara/tensor/basic.py
index 11c905119..8813af393 100644
--- a/aesara/tensor/basic.py
+++ b/aesara/tensor/basic.py
@@ -580,7 +580,6 @@ class TensorFromScalar(COp):
             if(py_%(z)s == NULL){
                 %(fail)s;
             }
-            Py_XINCREF(%(z)s);
             """
             % locals()
         )
```

Can you confirm whether this is the correct fix?

**Comment by brandonwillard** [comment]
> Can you confirm whether this is the correct fix?


Yes, that looks like the most likely source of the issue.  Feel free to open a PR.
