### ISSUE TITLE
AttributeError on import with new NumPy 1.22

### ISSUE THREAD

**Issue by michaelosthege** [aesara-devs/aesara#715]
## Description of your problem or feature request

Yesterdays NumPy 1.22.0 release broke some blas config settings.

I first saw it in a CI run today, and it was easily reproduced locally by installing the latest NumPy.

**Please provide the full traceback of any errors.**

```python
>>> import aesara
Traceback (most recent call last):
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 239, in fetch_val_for_key
    return self._aesara_cfg.get(section, option)
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 355, in __get__
    val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 243, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\__init__.py", line 79, in <module>
    from aesara import scalar, tensor
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\tensor\__init__.py", line 96, in <module>
    from aesara.tensor import (  # noqa
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\tensor\blas.py", line 166, in <module>
    from aesara.tensor.blas_headers import blas_header_text, blas_header_version
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\tensor\blas_headers.py", line 1015, in <module>
    if not config.blas__ldflags:
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 359, in __get__
    val_str = self.default()
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\link\c\cmodule.py", line 2628, in default_blas_ldflags
    blas_info = numpy.distutils.__config__.blas_opt_info
AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'
```

## Versions and main components

* Aesara version: 2.3.3
* ~Aesara config (`python -c "import aesara; print(aesara.config)"`)~
* Python version: confirmed for 3.8, 3.9
* Operating system: confirmed for Linux, Windows
* How did you install Aesara: pip

**Comment by kc611** [comment]
Same issue pops up in any Aesara test run we do right now. (For instance https://github.com/aesara-devs/aesara/runs/4680400825?check_suite_focus=true)
