### ISSUE TITLE
`tensor.zeros` fails with symbolic scalar values

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#775]
```python
import aesara.tensor as at

at.zeros([5]).eval()
at.zeros(5).eval()
at.zeros(at.constant([5])).eval()
at.zeros(at.constant(5)).eval()  # <- This fails
```
```python
Traceback (most recent call last):
  File "/home/ricardo/Documents/Projects/aesara/aesara/tensor/var.py", line 609, in __iter__
    for i in range(at.basic.get_vector_length(self)):
  File "/home/ricardo/Documents/Projects/aesara/aesara/tensor/__init__.py", line 74, in get_vector_length
    raise TypeError(f"Argument must be a vector; got {v.type}")
TypeError: Argument must be a vector; got TensorType(int8, ())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ricardo/Documents/Projects/aesara/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-b11de4c0b2ab>", line 6, in <module>
    at.zeros(at.constant(5)).eval()
  File "/home/ricardo/Documents/Projects/aesara/aesara/tensor/basic.py", line 993, in zeros
    return alloc(np.array(0, dtype=dtype), *shape)
  File "/home/ricardo/Documents/Projects/aesara/aesara/tensor/var.py", line 613, in __iter__
    raise TypeError(
TypeError: TensorType does not support iteration. Maybe you are using builtins.sum instead of aesara.tensor.math.sum? (Maybe .max?)

```

**Comment by danhphan** [comment]
Hi @ricardoV94, I'm working on this one :) Thanks

**Comment by ricardoV94** [comment]
Thanks!
