### ISSUE TITLE
`tensor.take` bug

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#786]
```python
import aesara.tensor as at
import numpy as np

x = np.zeros((3, 3))
at.take(x, np.eye(3, dtype=int))
```

```
Traceback (most recent call last):
  File "/home/ricardo/Documents/Projects/aesara/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-0de512d75688>", line 4, in <module>
    at.take(x, np.eye(3, dtype=int))
  File "/home/ricardo/Documents/Projects/aesara/aesara/tensor/subtensor.py", line 2777, in take
    elif axis < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by kc611** [comment]
I think the appropriate fix here is to replace:
https://github.com/aesara-devs/aesara/blob/55f54243cf88397b032ebc7121d1090ee91aea7d/aesara/tensor/subtensor.py#L2773-L2774
with
```python
    if axis is None:
        return advanced_subtensor(a.flatten(), indices)
```

Because the former, for some reason limited the `None` case to flattened indices.
