### ISSUE TITLE
`at.broadcast_shape` function does not work with tensor inputs

### ISSUE THREAD

**Issue by Sayam753** [aesara-devs/aesara#798]
**Please provide a minimal, self-contained, and reproducible example.**
```python
>>> import aesara.tensor as at
>>> shape1 = at.as_tensor_variable([3, 4])
>>> shape2 = at.as_tensor_variable([1, 4])
>>> at.broadcast_shape(shape1, shape2, arrays_are_shapes=True)
```

**Please provide the full traceback of any errors.**
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sayam/miniconda3/envs/pymc_dev/lib/python3.7/site-packages/aesara/tensor/extra_ops.py", line 1479, in broadcast_shape
    return broadcast_shape_iter(arrays, **kwargs)
  File "/Users/sayam/miniconda3/envs/pymc_dev/lib/python3.7/site-packages/aesara/tensor/extra_ops.py", line 1510, in broadcast_shape_iter
    max_dims = max(len(a) for a in arrays)
  File "/Users/sayam/miniconda3/envs/pymc_dev/lib/python3.7/site-packages/aesara/tensor/extra_ops.py", line 1510, in <genexpr>
    max_dims = max(len(a) for a in arrays)
TypeError: object of type 'TensorConstant' has no len()
```

**Please provide any additional information below.**

If the inputs to `at.broadcast_shape` are lists, it works correctly -

```python
>>> at.broadcast_shape([3, 4], [1, 4], arrays_are_shapes=True)
(3, 4)
```

## Versions and main components

* Aesara version: 2.3.6
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* Python version: python 3.7.7
* Operating system: MacOS
* How did you install Aesara: (conda/pip) pip

**Comment by brandonwillard** [comment]
With `arrays_are_shapes=True` set you are expected to pass `tuple`s of shapes.
