### ISSUE TITLE
Errors in cache updating logic with concurrent graph compiles

### ISSUE THREAD

**Issue by mattearllongshot** [aesara-devs/aesara#858]
## Description of your problem or feature request

Hello, we're developing an application which consists of multiple worker processes which start at the same time, each of which compiles an identical Aesara graph.  Here is a short example which reproduces the problem: 

```python
import multiprocessing

import aesara
import aesara.tensor as at
import numpy as np

def f(factor, barrier):
    a = at.vector()
    b = at.vector()
    barrier.wait()   # optional, try with or without
    f = aesara.function([a, b], at.sum(factor * at.dot(a, b)))
    return f(np.array([1, 2, 3]), np.array([4, 5, 6]))

num_procs = 20

while True:
    factor = np.random.random()   # random factor to prevent caching between runs
    print(f'{factor=}')
    barrier = multiprocessing.Barrier(num_procs)
    procs = [multiprocessing.Process(target=f, args=(factor, barrier)) for i in range(num_procs)]
    for proc in procs:
        proc.start()
    for proc in procs:
        proc.join()

    exit_codes = [proc.exitcode for proc in procs]
    print(f'{exit_codes=}')
    if any(exit_code != 0 for exit_code in exit_codes):
        break
```

Each loop will run 20 parallel compilations of an identical graph (the graph is different for each loop).  Here is some example output:

```
factor=0.8232652038645821
exit_codes=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
factor=0.6012850336942555
exit_codes=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
factor=0.3702983019245454
exit_codes=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
factor=0.10300371685537746
WARNING (aesara.link.c.cmodule): Deleting (broken cache directory [EOF]): /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.10-x86_64-3.8.12-64/tmp74cpm5pp
WARNING (aesara.link.c.cmodule): Deleting (broken cache directory [EOF]): /home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.10-x86_64-3.8.12-64/tmp74cpm5pp
Process Process-67:
Traceback (most recent call last):
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/vm.py", line 1112, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1198, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1133, in __compile__
    thunk, module = self.cthunk_factory(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1629, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 1185, in module_from_key
    module = self._get_from_hash(module_hash, key)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 1088, in _get_from_hash
    key_data.add_key(key, save_pkl=bool(key[0]))
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 528, in add_key
    self.save_pkl()
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 549, in save_pkl
    with open(self.key_pkl, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.10-x86_64-3.8.12-64/tmp74cpm5pp/key.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/matthew/junk/aesara_race.py", line 11, in f
    f = aesara.function([a, b], at.sum(factor * at.dot(a, b)))
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/compile/function/__init__.py", line 337, in function
    fn = pfunc(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/compile/function/pfunc.py", line 363, in pfunc
    return orig_function(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/compile/function/types.py", line 1743, in orig_function
    fn = m.create(defaults)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/compile/function/types.py", line 1638, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/basic.py", line 254, in make_thunk
    return self.make_all(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/vm.py", line 1121, in make_all
    raise_with_op(fgraph, node)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/utils.py", line 538, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/vm.py", line 1112, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/op.py", line 131, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/op.py", line 96, in make_c_thunk
    outputs = cl.make_thunk(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1198, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1133, in __compile__
    thunk, module = self.cthunk_factory(
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/basic.py", line 1629, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 1185, in module_from_key
    module = self._get_from_hash(module_hash, key)
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 1088, in _get_from_hash
    key_data.add_key(key, save_pkl=bool(key[0]))
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 528, in add_key
    self.save_pkl()
  File "/mnt/data/conda/envs/mbt-py38-light/lib/python3.8/site-packages/aesara/link/c/cmodule.py", line 549, in save_pkl
    with open(self.key_pkl, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matthew/.aesara/compiledir_Linux-4.15--generic-x86_64-with-glibc2.10-x86_64-3.8.12-64/tmp74cpm5pp/key.pkl'
Apply node that caused the error: Elemwise{Mul}[(0, 1)](TensorConstant{0.10300371685537746}, InplaceDimShuffle{}.0)
Toposort index: 4
Inputs types: [TensorType(float64, ()), TensorType(float64, ())]

HINT: Use a linker other than the C linker to print the inputs' shapes and strides.
HINT: Re-running with most Aesara optimizations disabled could provide a back-trace showing when this node was created. This can be done by setting the Aesara flag 'optimizer=fast_compile'. If that does not work, Aesara optimizations can be disabled with 'optimizer=None'.
HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.
exit_codes=[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

The number of failing processes seems to vary.  To reproduce you might need to increase `num_procs` or perhaps make the function being compiled more complex, as it seems to be timing dependent.

## Versions and main components

* Aesara version:  2.5.1
* Aesara config (`python -c "import aesara; print(aesara.config)"`)  [aesara_config.txt](https://github.com/aesara-devs/aesara/files/8233404/aesara_config.txt)
* Python version: 3.8.12
* Operating system: Ubuntu 18.04.6 LTS
* How did you install Aesara: conda (mamba)

**Comment by mattearllongshot** [comment]
I did some debugging around the `EOFError` that caused the initial `Deleting (broken cache directory [EOF])` message.  The `EOFError` is raised in a call to `ModuleCache.refresh` from `ModuleCache.__init__`.  If I put a `with lock_ctx():` call around that call it seems to fix the problem.  Is this the right fix?

```diff
diff --git a/aesara/link/c/cmodule.py b/aesara/link/c/cmodule.py
index 103a9d758..517d69539 100644
--- a/aesara/link/c/cmodule.py
+++ b/aesara/link/c/cmodule.py
@@ -708,7 +708,8 @@ class ModuleCache:
         self.time_spent_in_check_key = 0

         if do_refresh:
-            self.refresh()
+            with lock_ctx():
+                self.refresh()

     age_thresh_use = config.cmodule__age_thresh_use  # default 24 days
     """
```

**Comment by brandonwillard** [comment]
> I did some debugging around the `EOFError` that caused the initial `Deleting (broken cache directory [EOF])` message. The `EOFError` is raised in a call to `ModuleCache.refresh` from `ModuleCache.__init__`. If I put a `with lock_ctx():` call around that call it seems to fix the problem. Is this the right fix?
> 
> ```diff
> diff --git a/aesara/link/c/cmodule.py b/aesara/link/c/cmodule.py
> index 103a9d758..517d69539 100644
> --- a/aesara/link/c/cmodule.py
> +++ b/aesara/link/c/cmodule.py
> @@ -708,7 +708,8 @@ class ModuleCache:
>          self.time_spent_in_check_key = 0
> 
>          if do_refresh:
> -            self.refresh()
> +            with lock_ctx():
> +                self.refresh()
> 
>      age_thresh_use = config.cmodule__age_thresh_use  # default 24 days
>      """
> ```

Seems like it might be; thanks!

**Comment by mattearllongshot** [comment]
Shall I raise a PR for the above fix?

**Comment by brandonwillard** [comment]
> Shall I raise a PR for the above fix?

That would be much appreciated.  

The real trick to making these kinds of changes is the testing.  It looks like you have the foundation for a unit test, but I haven't been able to reproduce the issue on my machine&mdash;although that's not saying much.  

If the issue can be reproduced somewhat regularly in CI, then that's fine, so feel free to set up a draft PR that demonstrates the issue (e.g. the test without the fix) and then rebase it with the fix afterward.

**Comment by brandonwillard** [comment]
Nevermind, I was just able to reproduce it, but it took too long for a unit test, so we'll need to tweak your MWE so that it reproduces the issue more quickly.

**Comment by brandonwillard** [comment]
For example, this set of small alterations appears to reproduce the problem much more quickly on my machine:
```python
import multiprocessing

import aesara
import aesara.tensor as at
import numpy as np


def f_build(factor, barrier):
    a = at.vector()
    # Some of the caching issues arise during constant folding within the
    # optimization passes, so we need these config changes to prevent the
    # exceptions from being caught
    with aesara.config.change_flags(on_opt_error="raise", on_shape_error="raise"):
        f = aesara.function([a], factor * a)
        return f(np.array([1]))


num_procs = 20
rng = np.random.default_rng(209)

for i in range(1000):
    # A random, constant input to prevent caching between runs
    factor = rng.random()
    barrier = multiprocessing.Barrier(num_procs)
    procs = [
        multiprocessing.Process(target=f_build, args=(factor, barrier))
        for i in range(num_procs)
    ]
    for proc in procs:
        proc.start()
    for proc in procs:
        proc.join()

    assert not any(exit_code != 0 for exit_code in [proc.exitcode for proc in procs])

```

**Comment by mattearllongshot** [comment]
Do you know what the race is?  We could potentially monkey patch `pickle.load` and `pickle.dump` (assuming these are the only calls involved) to coordinate the right order of events to trigger the bug.  I tried adding a random sleep into `pickle.dump` since I figured the issue is with the read during while the write is in progress, but unfortunately it didn't appear to make the bug any more reliable:

```python
orig_dump = pickle.dump
@functools.wraps(orig_dump)
def patched_dump(*args, **kwargs):
    print(os.getpid(), args[1], 'dump')
    out = orig_dump(*args, **kwargs)
    time.sleep(random.random() * .1)
    print(os.getpid(), 'dumped')
    return out
pickle.dump = patched_dump

orig_load = pickle.load
@functools.wraps(orig_load)
def patched_load(*args, **kwargs):
    print(os.getpid(), args[0], 'load')
    out = orig_load(*args, **kwargs)
    print(os.getpid(), 'loaded')
    return out
pickle.load = patched_load
```
It does seem that triggering the `broken cache directory [EOF]` error is the first step, though I'm a bit lost as to how to best get into this state, not knowing the design.  Any ideas?

**Comment by mattearllongshot** [comment]
I've managed to produce a script which reliably reproduces the `EOFError`.  There are two processes involved, it occurs when the first process is doing its initial module cache refresh and attempts to read a key file that is being written by the second process.  To be more precise, the sequence of events is:

i) Process 1 starts writing key file after compiling.
ii) Process 0 runs listdir in the `refresh()` call triggered by `ModuleCache().__init__`.
iii) Process 0 attempts to read the key file, still in the same `refresh()` call, triggering the `EOFError`.
iv) Process 1 finishes writing the key file.

Unfortunately we see this almost all the time since we're deploying parallel workloads with dozens of processes per machine, with several machines in the cluster.

Here is the script to reproduce it:

```python
import functools
import multiprocessing
import os
import pickle
import sys
import traceback

import aesara
import aesara.tensor as at
import numpy as np

SHOW_STACKS = False

dump_started_event = multiprocessing.Event()
load_finished_event = multiprocessing.Event()

global_proc_num = None

orig_dump = pickle.dump
@functools.wraps(orig_dump)
def patched_dump(*args, **kwargs):
    if global_proc_num == 1:
        if SHOW_STACKS and not dump_started_event.is_set():
            print(global_proc_num, 'dump')
            traceback.print_stack(file=sys.stdout)
        dump_started_event.set()
        load_finished_event.wait(timeout=5)   # prevent a deadlock when fix is applied
    out = orig_dump(*args, **kwargs)
    return out
pickle.dump = patched_dump

orig_load = pickle.load
@functools.wraps(orig_load)
def patched_load(*args, **kwargs):
    try:
        out = orig_load(*args, **kwargs)
    finally:
        if global_proc_num == 0:
            if SHOW_STACKS and not load_finished_event.is_set():
                print(global_proc_num, 'load')
                traceback.print_stack(file=sys.stdout)
            load_finished_event.set()
    return out
pickle.load = patched_load

orig_listdir = os.listdir
@functools.wraps(orig_listdir)
def patched_listdir(*args, **kwargs):
    if global_proc_num == 0:
        dump_started_event.wait(timeout=5)
    out = orig_listdir(*args, **kwargs)
    return out
os.listdir = patched_listdir

def f(proc_num):
    global global_proc_num
    global_proc_num = proc_num
    a = at.vector()
    aesara.function([a], at.sum(a))

procs = [multiprocessing.Process(target=f, args=(proc_num,)) for proc_num in range(2)]
for proc in procs:
    proc.start()
for proc in procs:
    proc.join()
```

For this script to work you must clear your cache directory first (eg. remove `~/.aesara/compiledir_...`), since the orchestration here requires that the first `load` call corresponds with the same file as the first `dump` call, but in general the bug still exists with a populated cache dir.   When this runs you should see the `WARNING (aesara.link.c.cmodule): Deleting (broken cache directory [EOF])` message.  Set `SHOW_STACKS = True` to print the stack traces during the load / dump calls.

I believe the `FileNotFoundError` from my original post follows on as a consequence of the cache directory being removed, since it references the removed path.

Could this serve as the basis for a suitable unit test so that we can raise a PR to add the extra lock?

**Comment by brandonwillard** [comment]
> Could this serve as the basis for a suitable unit test so that we can raise a PR to add the extra lock?

Absolutely; this looks like a fantastically direct reproduction of a very elusive type of issue!

My only recommendation is to use something like `unittest.mock` instead of monkey patching so that post-test clean-up is easier and/or more consistent.

**Comment by mattearllongshot** [comment]
Here's what I've got so far:
```python
import multiprocessing
import os
import pickle
import unittest.mock

import aesara
import aesara.tensor as at
import numpy as np


def test_cache_race():
    def patched_listdir(*args, **kwargs):
        if global_proc_num == 0:
            dump_started_event.wait(timeout=5)
        out = orig_listdir(*args, **kwargs)
        return out

    def patched_load(*args, **kwargs):
        try:
            out = orig_load(*args, **kwargs)
        finally:
            if global_proc_num == 0:
                load_finished_event.set()
        return out

    def patched_dump(*args, **kwargs):
        if global_proc_num == 1:
            dump_started_event.set()
            load_finished_event.wait(timeout=5)
        out = orig_dump(*args, **kwargs)
        return out

    def f(proc_num):
        nonlocal global_proc_num
        global_proc_num = proc_num
        a = at.vector()
        aesara.function([a], at.sum(a))

    orig_listdir = os.listdir
    orig_load = pickle.load
    orig_dump = pickle.dump

    dump_started_event = multiprocessing.Event()
    load_finished_event = multiprocessing.Event()
    global_proc_num = None

    with unittest.mock.patch('os.listdir', wraps=patched_listdir), \
          unittest.mock.patch('pickle.load', wraps=patched_load), \
          unittest.mock.patch('pickle.dump', wraps=patched_dump):

        procs = [multiprocessing.Process(target=f, args=(proc_num,)) for proc_num in range(2)]
        for proc in procs:
            proc.start()
        for proc in procs:
            proc.join()
```

It's missing a way to clear the cache dir.  I was thinking to do this I could create a temporary directory and pass this in a `with conda.change_flags(f"compiledir={tmpdir}")` block, although reading the docs it looks like I might not be able to change this particular setting?

**Comment by mattearllongshot** [comment]
See https://aesara.readthedocs.io/en/latest/library/config.html#config.compiledir:
> This flag’s value cannot be modified during program execution.

**Comment by brandonwillard** [comment]
> It's missing a way to clear the cache dir. I was thinking to do this I could create a temporary directory and pass this in a `with conda.change_flags(f"compiledir={tmpdir}")` block, although reading the docs it looks like I might not be able to change this particular setting?

Yes, that's an unfortunate Theano design decision we've inherited.  It's possible to work around this by setting `aesara.config._config_var_dict["compiledir"].val` directly, but this should be done in a context manager with a `try ... finally` block, so that it's sure to be cleaned up properly afterward.

**Comment by brandonwillard** [comment]
@mattearllongshot, do you still want to open a PR for this?  If not, one of us can put together a PR based on the discussion here.

**Comment by mattearllongshot** [comment]
Sorry, I only just saw this.  If you want to create a PR that would be great.  Thanks

**Comment by brandonwillard** [comment]
I'm not able to reproduce the issue with the test in https://github.com/aesara-devs/aesara/issues/858#issuecomment-1080775108.

Also, here's a way to change the compilation directory and obtain a `ModuleCache` object that can be arbitrarily manipulated:
```python
import tempfile
from unittest.mock import patch

import aesara
from aesara.link.c.cmodule import ModuleCache
from aesara.link.c.basic import get_module_cache


with tempfile.TemporaryDirectory() as dir_name:

    mod_cache = ModuleCache(dir_name)

    compiledir_prop = aesara.config._config_var_dict["compiledir"]

    with patch.object(compiledir_prop, "val", dir_name, create=True), \
         patch.object(aesara.link.c.cmodule, "_module_cache", mod_cache):

        assert get_module_cache() is mod_cache
        assert aesara.config.compiledir == dir_name

```

**Comment by mattearllongshot** [comment]
WIth #969  my repro script no longer hits the race.  Thanks for fixing!
